### PR TITLE
Adding UNHCR, IFRC and removing Norway MFA

### PR DESCRIPTION
**Pull request by wendyrogers**
Registry ids added for IFRC and UNHCR. Also Norway Ministry of Foreign Affairs removed as not publishing any hum data

### CODE REVIEW

**Comment by petyakangalova-personal** [comment]
@wendyrogers first published date should be added and also need to check baseline values before merging.

**Review by samuele-mattiuzzo — CHANGES_REQUESTED** [review]
First published date should be added and also need to check baseline values before merging, as per Petya's comment

**Comment by wendyrogers** [comment]
Changes now made to add first published dates for both UNHCR and IFRC. Baseline values for both are zero

**Review by petyakangalova-personal — APPROVED** [review]
Correct publisher ids, first published dates and baseline values have been entered so happy to approve.

**Review by samuele-mattiuzzo — APPROVED** [review]

**Comment by andylolz** [comment]
@samuele-mattiuzzo If you’re deploying, any chance of taking a look at #85 before you do? It’s a quick (15 character) change that makes the GB dashboard significantly more legible.

I don’t mind either way – just seemed opportune.

**Comment by wendyrogers** [comment]
@samuele-mattiuzzo just to add that I would agree with @andylolz if it is possible to include. TIA

**Pull request merged**
